import JSZip from 'jszip';
import { FileStore } from './file-store';
import { FilePartitionMetadata } from './indexeddb-partitioner';

/**
 * Generate a ZIP blob for a partition from IndexedDB
 */
export async function generatePartZipFromIndexedDB(
  partition: FilePartitionMetadata,
  totalParts: number,
  compressionLevel: number = 6
): Promise<Blob> {
  const zip = new JSZip();
  
  // Load files for this partition from IndexedDB
  const files = await FileStore.getPartitionFiles(partition.fileIds);
  
  // Add files to ZIP
  for (const file of files) {
    zip.file(file.path, file.blob);
  }
  
  // Add README
  const readme = createReadmeContent(partition.partNumber, totalParts);
  zip.file('README.txt', readme);
  
  // Add part marker
  zip.file(`.part-${String(partition.partNumber).padStart(2, '0')}`, '');
  
  // Generate ZIP blob
  return await zip.generateAsync({
    type: 'blob',
    compression: 'DEFLATE',
    compressionOptions: { level: compressionLevel }
  });
}

function createReadmeContent(partNumber: number, totalParts: number): string {
  return `Website Download - Part ${partNumber} of ${totalParts}

This is part ${partNumber} of a ${totalParts}-part download.

To extract the complete website:
1. Download all ${totalParts} parts
2. Extract all parts to the SAME folder
3. The files will merge automatically

Generated by Website Downloader Extension
`;
}
