import { Button } from "../../components/Button";

interface PermissionRequestProps {
  onRequestPermission: () => Promise<void>;
  requesting: boolean;
}

export function PermissionRequest({
  onRequestPermission,
  requesting,
}: PermissionRequestProps) {
  return (
    <div className="bg-blue-50 border border-blue-200 rounded-lg p-6 text-center">
      <div className="mb-4">
        <div className="text-4xl mb-2">🔒</div>
        <h2 className="text-xl font-semibold text-gray-900 mb-2">
          Storage Permission Required
        </h2>
        <p className="text-gray-600 mb-4">
          To submit and manage feature requests, we generate a unique ID for you
          and require permission to store the ID locally.
          <br />
          This helps us track your requests and provide a better experience.
        </p>
        <div className="text-sm text-gray-500 mb-4">
          <p>
            <strong>What we store:</strong>
          </p>
          <ul className="list-disc list-inside mt-1 space-y-1">
            <li>A unique user ID (generated by our server)</li>
            <li>No personal information</li>
          </ul>
        </div>
      </div>

      <Button
        onClick={onRequestPermission}
        disabled={requesting}
        className="px-6 py-2"
      >
        {requesting ? "Requesting Permission..." : "Enable Storage Permission"}
      </Button>

      <p className="text-xs text-gray-500 mt-3">
        You can revoke this permission at any time in your browser's extension
        settings.
      </p>
    </div>
  );
}
