# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import archive_pb2 as archive__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in archive_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ArchiveServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.IngestPage = channel.unary_unary(
                '/archive.ArchiveService/IngestPage',
                request_serializer=archive__pb2.IngestPageRequest.SerializeToString,
                response_deserializer=archive__pb2.IngestPageResponse.FromString,
                _registered_method=True)
        self.GetPage = channel.unary_unary(
                '/archive.ArchiveService/GetPage',
                request_serializer=archive__pb2.GetPageRequest.SerializeToString,
                response_deserializer=archive__pb2.PageResponse.FromString,
                _registered_method=True)
        self.ListPages = channel.unary_unary(
                '/archive.ArchiveService/ListPages',
                request_serializer=archive__pb2.ListPagesRequest.SerializeToString,
                response_deserializer=archive__pb2.ListPagesResponse.FromString,
                _registered_method=True)
        self.DeletePage = channel.unary_unary(
                '/archive.ArchiveService/DeletePage',
                request_serializer=archive__pb2.DeletePageRequest.SerializeToString,
                response_deserializer=archive__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.GetPageContent = channel.unary_unary(
                '/archive.ArchiveService/GetPageContent',
                request_serializer=archive__pb2.GetPageContentRequest.SerializeToString,
                response_deserializer=archive__pb2.PageContentResponse.FromString,
                _registered_method=True)
        self.GetArchiveFile = channel.unary_unary(
                '/archive.ArchiveService/GetArchiveFile',
                request_serializer=archive__pb2.GetArchiveFileRequest.SerializeToString,
                response_deserializer=archive__pb2.ArchiveFileResponse.FromString,
                _registered_method=True)


class ArchiveServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def IngestPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ListPages(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeletePage(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetPageContent(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetArchiveFile(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ArchiveServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'IngestPage': grpc.unary_unary_rpc_method_handler(
                    servicer.IngestPage,
                    request_deserializer=archive__pb2.IngestPageRequest.FromString,
                    response_serializer=archive__pb2.IngestPageResponse.SerializeToString,
            ),
            'GetPage': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPage,
                    request_deserializer=archive__pb2.GetPageRequest.FromString,
                    response_serializer=archive__pb2.PageResponse.SerializeToString,
            ),
            'ListPages': grpc.unary_unary_rpc_method_handler(
                    servicer.ListPages,
                    request_deserializer=archive__pb2.ListPagesRequest.FromString,
                    response_serializer=archive__pb2.ListPagesResponse.SerializeToString,
            ),
            'DeletePage': grpc.unary_unary_rpc_method_handler(
                    servicer.DeletePage,
                    request_deserializer=archive__pb2.DeletePageRequest.FromString,
                    response_serializer=archive__pb2.StatusResponse.SerializeToString,
            ),
            'GetPageContent': grpc.unary_unary_rpc_method_handler(
                    servicer.GetPageContent,
                    request_deserializer=archive__pb2.GetPageContentRequest.FromString,
                    response_serializer=archive__pb2.PageContentResponse.SerializeToString,
            ),
            'GetArchiveFile': grpc.unary_unary_rpc_method_handler(
                    servicer.GetArchiveFile,
                    request_deserializer=archive__pb2.GetArchiveFileRequest.FromString,
                    response_serializer=archive__pb2.ArchiveFileResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'archive.ArchiveService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('archive.ArchiveService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ArchiveService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def IngestPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archive.ArchiveService/IngestPage',
            archive__pb2.IngestPageRequest.SerializeToString,
            archive__pb2.IngestPageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archive.ArchiveService/GetPage',
            archive__pb2.GetPageRequest.SerializeToString,
            archive__pb2.PageResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ListPages(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archive.ArchiveService/ListPages',
            archive__pb2.ListPagesRequest.SerializeToString,
            archive__pb2.ListPagesResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeletePage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archive.ArchiveService/DeletePage',
            archive__pb2.DeletePageRequest.SerializeToString,
            archive__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetPageContent(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archive.ArchiveService/GetPageContent',
            archive__pb2.GetPageContentRequest.SerializeToString,
            archive__pb2.PageContentResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetArchiveFile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/archive.ArchiveService/GetArchiveFile',
            archive__pb2.GetArchiveFileRequest.SerializeToString,
            archive__pb2.ArchiveFileResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
