# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: auth.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'auth.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nauth.proto\x12\x04\x61uth\"@\n\x0fRegisterRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\"/\n\x0cLoginRequest\x12\r\n\x05\x65mail\x18\x01 \x01(\t\x12\x10\n\x08password\x18\x02 \x01(\t\"\x1e\n\rVerifyRequest\x12\r\n\x05token\x18\x01 \x01(\t\"\'\n\x0eRefreshRequest\x12\x15\n\rrefresh_token\x18\x01 \x01(\t\" \n\rLogoutRequest\x12\x0f\n\x07user_id\x18\x01 \x01(\t\"f\n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\r\n\x05\x65mail\x18\x02 \x01(\t\x12\x0c\n\x04name\x18\x03 \x01(\t\x12\x0c\n\x04plan\x18\x04 \x01(\t\x12\x13\n\x0bis_verified\x18\x05 \x01(\x08\x12\x12\n\ncreated_at\x18\x06 \x01(\t\"i\n\x0c\x41uthResponse\x12\x14\n\x0c\x61\x63\x63\x65ss_token\x18\x01 \x01(\t\x12\x15\n\rrefresh_token\x18\x02 \x01(\t\x12\x12\n\nexpires_at\x18\x03 \x01(\x03\x12\x18\n\x04user\x18\x04 \x01(\x0b\x32\n.auth.User\"M\n\x0eVerifyResponse\x12\r\n\x05valid\x18\x01 \x01(\x08\x12\x0f\n\x07user_id\x18\x02 \x01(\t\x12\r\n\x05\x65mail\x18\x03 \x01(\t\x12\x0c\n\x04plan\x18\x04 \x01(\t\"2\n\x0eStatusResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t2\x94\x02\n\x0b\x41uthService\x12\x35\n\x08Register\x12\x15.auth.RegisterRequest\x1a\x12.auth.AuthResponse\x12/\n\x05Login\x12\x12.auth.LoginRequest\x1a\x12.auth.AuthResponse\x12\x33\n\x06Verify\x12\x13.auth.VerifyRequest\x1a\x14.auth.VerifyResponse\x12\x33\n\x07Refresh\x12\x14.auth.RefreshRequest\x1a\x12.auth.AuthResponse\x12\x33\n\x06Logout\x12\x13.auth.LogoutRequest\x1a\x14.auth.StatusResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'auth_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_REGISTERREQUEST']._serialized_start=20
  _globals['_REGISTERREQUEST']._serialized_end=84
  _globals['_LOGINREQUEST']._serialized_start=86
  _globals['_LOGINREQUEST']._serialized_end=133
  _globals['_VERIFYREQUEST']._serialized_start=135
  _globals['_VERIFYREQUEST']._serialized_end=165
  _globals['_REFRESHREQUEST']._serialized_start=167
  _globals['_REFRESHREQUEST']._serialized_end=206
  _globals['_LOGOUTREQUEST']._serialized_start=208
  _globals['_LOGOUTREQUEST']._serialized_end=240
  _globals['_USER']._serialized_start=242
  _globals['_USER']._serialized_end=344
  _globals['_AUTHRESPONSE']._serialized_start=346
  _globals['_AUTHRESPONSE']._serialized_end=451
  _globals['_VERIFYRESPONSE']._serialized_start=453
  _globals['_VERIFYRESPONSE']._serialized_end=530
  _globals['_STATUSRESPONSE']._serialized_start=532
  _globals['_STATUSRESPONSE']._serialized_end=582
  _globals['_AUTHSERVICE']._serialized_start=585
  _globals['_AUTHSERVICE']._serialized_end=861
# @@protoc_insertion_point(module_scope)
