# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import share_pb2 as share__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in share_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ShareServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateShareLink = channel.unary_unary(
                '/share.ShareService/CreateShareLink',
                request_serializer=share__pb2.CreateShareLinkRequest.SerializeToString,
                response_deserializer=share__pb2.ShareLinkResponse.FromString,
                _registered_method=True)
        self.GetShareLink = channel.unary_unary(
                '/share.ShareService/GetShareLink',
                request_serializer=share__pb2.GetShareLinkRequest.SerializeToString,
                response_deserializer=share__pb2.ShareLinkResponse.FromString,
                _registered_method=True)
        self.RevokeShareLink = channel.unary_unary(
                '/share.ShareService/RevokeShareLink',
                request_serializer=share__pb2.RevokeShareLinkRequest.SerializeToString,
                response_deserializer=share__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ValidateToken = channel.unary_unary(
                '/share.ShareService/ValidateToken',
                request_serializer=share__pb2.ValidateTokenRequest.SerializeToString,
                response_deserializer=share__pb2.ValidateShareResponse.FromString,
                _registered_method=True)


class ShareServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateShareLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetShareLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RevokeShareLink(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ValidateToken(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ShareServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateShareLink': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateShareLink,
                    request_deserializer=share__pb2.CreateShareLinkRequest.FromString,
                    response_serializer=share__pb2.ShareLinkResponse.SerializeToString,
            ),
            'GetShareLink': grpc.unary_unary_rpc_method_handler(
                    servicer.GetShareLink,
                    request_deserializer=share__pb2.GetShareLinkRequest.FromString,
                    response_serializer=share__pb2.ShareLinkResponse.SerializeToString,
            ),
            'RevokeShareLink': grpc.unary_unary_rpc_method_handler(
                    servicer.RevokeShareLink,
                    request_deserializer=share__pb2.RevokeShareLinkRequest.FromString,
                    response_serializer=share__pb2.StatusResponse.SerializeToString,
            ),
            'ValidateToken': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateToken,
                    request_deserializer=share__pb2.ValidateTokenRequest.FromString,
                    response_serializer=share__pb2.ValidateShareResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'share.ShareService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('share.ShareService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ShareService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateShareLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/share.ShareService/CreateShareLink',
            share__pb2.CreateShareLinkRequest.SerializeToString,
            share__pb2.ShareLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetShareLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/share.ShareService/GetShareLink',
            share__pb2.GetShareLinkRequest.SerializeToString,
            share__pb2.ShareLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RevokeShareLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/share.ShareService/RevokeShareLink',
            share__pb2.RevokeShareLinkRequest.SerializeToString,
            share__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ValidateToken(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/share.ShareService/ValidateToken',
            share__pb2.ValidateTokenRequest.SerializeToString,
            share__pb2.ValidateShareResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
