export type MessageAction =
  | "PANEL_MESSAGE"
  | "START_SCROLL"
  | "DOWNLOAD_DONE"
  | "START_DOWNLOAD"
  | "CHECK_ONLINE_STATUS";

export const messageActions: Record<MessageAction, MessageAction> = {
  PANEL_MESSAGE: "PANEL_MESSAGE",
  START_SCROLL: "START_SCROLL",
  DOWNLOAD_DONE: "DOWNLOAD_DONE",
  START_DOWNLOAD: "START_DOWNLOAD",
  CHECK_ONLINE_STATUS: "CHECK_ONLINE_STATUS",
};
