export type MessageAction =
  | "PANEL_MESSAGE"
  | "START_SCROLL"
  | "DOWNLOAD_DONE"
  | "DOWNLOAD_COMPLETE"
  | "DOWNLOAD_FAILED"
  | "DOWNLOAD_CANCELLED"
  | "START_DOWNLOAD"
  | "CHECK_ONLINE_STATUS"
  | "INITIALIZE_DIFFERENTIAL_SCRAPING"
  | "SCROLL_AND_EXTRACT_DIFF"
  | "START_INCREMENTAL_DOWNLOAD"
  | "SCRAPER_PAUSE"
  | "SCRAPER_RESUME"
  | "SCRAPER_STOP"
  | "PANEL_CREATE_DOWNLOAD"
  | "PANEL_PING";

export const messageActions: Record<MessageAction, MessageAction> = {
  PANEL_MESSAGE: "PANEL_MESSAGE",
  START_SCROLL: "START_SCROLL",
  DOWNLOAD_DONE: "DOWNLOAD_DONE",
  DOWNLOAD_COMPLETE: "DOWNLOAD_COMPLETE",
  DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
  DOWNLOAD_CANCELLED: "DOWNLOAD_CANCELLED",
  START_DOWNLOAD: "START_DOWNLOAD",
  CHECK_ONLINE_STATUS: "CHECK_ONLINE_STATUS",
  INITIALIZE_DIFFERENTIAL_SCRAPING: "INITIALIZE_DIFFERENTIAL_SCRAPING",
  SCROLL_AND_EXTRACT_DIFF: "SCROLL_AND_EXTRACT_DIFF",
  START_INCREMENTAL_DOWNLOAD: "START_INCREMENTAL_DOWNLOAD",
  SCRAPER_PAUSE: "SCRAPER_PAUSE",
  SCRAPER_RESUME: "SCRAPER_RESUME",
  SCRAPER_STOP: "SCRAPER_STOP",
  PANEL_CREATE_DOWNLOAD: "PANEL_CREATE_DOWNLOAD",
  PANEL_PING: "PANEL_PING",
};
