export type MessageAction =
  | "PANEL_MESSAGE"
  | "START_SCROLL"
  | "DOWNLOAD_DONE"
  | "DOWNLOAD_COMPLETE"
  | "DOWNLOAD_FAILED"
  | "DOWNLOAD_CANCELLED"
  | "START_DOWNLOAD"
  | "CHECK_ONLINE_STATUS"
  | "INITIALIZE_DIFFERENTIAL_SCRAPING"
  | "SCROLL_AND_EXTRACT_DIFF"
  | "SCRAPER_PAUSE"
  | "SCRAPER_RESUME"
  | "SCRAPER_STOP"
  | "PANEL_PING"
  // Server-mode message actions (task 13.1)
  | "SERVER_CREATE_SESSION"
  | "SERVER_UPLOAD_HTML_CHUNK"
  | "SERVER_SCRAPE_COMPLETE"
  | "SERVER_UPLOAD_RESOURCE"
  | "SERVER_UPLOAD_CONTENT"
  | "SERVER_FINALIZE_SESSION"
  | "SERVER_SESSION_STATUS"
  | "SERVER_HEALTH_CHECK"
  | "DOWNLOAD_INTERRUPTED"
  | "CHECK_INTERRUPTED_DOWNLOAD"
  | "RESUME_SERVER_DOWNLOAD"
  | "DISMISS_INTERRUPTED_DOWNLOAD"
  // PagePocket cloud upload message actions
  | "PAGEPOCKET_UPLOAD_START"
  | "PAGEPOCKET_UPLOAD_PROGRESS"
  | "PAGEPOCKET_UPLOAD_COMPLETE"
  | "PAGEPOCKET_UPLOAD_ERROR";

export const messageActions: Record<MessageAction, MessageAction> = {
  PANEL_MESSAGE: "PANEL_MESSAGE",
  START_SCROLL: "START_SCROLL",
  DOWNLOAD_DONE: "DOWNLOAD_DONE",
  DOWNLOAD_COMPLETE: "DOWNLOAD_COMPLETE",
  DOWNLOAD_FAILED: "DOWNLOAD_FAILED",
  DOWNLOAD_CANCELLED: "DOWNLOAD_CANCELLED",
  START_DOWNLOAD: "START_DOWNLOAD",
  CHECK_ONLINE_STATUS: "CHECK_ONLINE_STATUS",
  INITIALIZE_DIFFERENTIAL_SCRAPING: "INITIALIZE_DIFFERENTIAL_SCRAPING",
  SCROLL_AND_EXTRACT_DIFF: "SCROLL_AND_EXTRACT_DIFF",
  SCRAPER_PAUSE: "SCRAPER_PAUSE",
  SCRAPER_RESUME: "SCRAPER_RESUME",
  SCRAPER_STOP: "SCRAPER_STOP",
  PANEL_PING: "PANEL_PING",
  // Server-mode message actions (task 13.1)
  SERVER_CREATE_SESSION: "SERVER_CREATE_SESSION",
  SERVER_UPLOAD_HTML_CHUNK: "SERVER_UPLOAD_HTML_CHUNK",
  SERVER_SCRAPE_COMPLETE: "SERVER_SCRAPE_COMPLETE",
  SERVER_UPLOAD_RESOURCE: "SERVER_UPLOAD_RESOURCE",
  SERVER_UPLOAD_CONTENT: "SERVER_UPLOAD_CONTENT",
  SERVER_FINALIZE_SESSION: "SERVER_FINALIZE_SESSION",
  SERVER_SESSION_STATUS: "SERVER_SESSION_STATUS",
  SERVER_HEALTH_CHECK: "SERVER_HEALTH_CHECK",
  DOWNLOAD_INTERRUPTED: "DOWNLOAD_INTERRUPTED",
  CHECK_INTERRUPTED_DOWNLOAD: "CHECK_INTERRUPTED_DOWNLOAD",
  RESUME_SERVER_DOWNLOAD: "RESUME_SERVER_DOWNLOAD",
  DISMISS_INTERRUPTED_DOWNLOAD: "DISMISS_INTERRUPTED_DOWNLOAD",
  // PagePocket cloud upload message actions
  PAGEPOCKET_UPLOAD_START: "PAGEPOCKET_UPLOAD_START",
  PAGEPOCKET_UPLOAD_PROGRESS: "PAGEPOCKET_UPLOAD_PROGRESS",
  PAGEPOCKET_UPLOAD_COMPLETE: "PAGEPOCKET_UPLOAD_COMPLETE",
  PAGEPOCKET_UPLOAD_ERROR: "PAGEPOCKET_UPLOAD_ERROR",
};
